### ISSUE TITLE
Design Scholarship page

### ISSUE THREAD

**Issue by chehak123** [chehak123/GirlMeetup#14]
This page would list
1. scholarship programs
2. Important Coding contests like codejam I/o
3. Hackathons especially for women
4. Other related opportunities

Each of them must be listed under different sections.

**Comment by pawki07** [comment]
Do we need to design a page using html?

**Comment by chehak123** [comment]
@pawki07 You need to design it using bootstrap

**Comment by pawki07** [comment]
I can work on this issue. It may take around 5-6 days to design it.

**Comment by chehak123** [comment]
This issue needs to be completed in 3 days as it is a medium level issue

**Comment by pawki07** [comment]
I will try to complete it in 3 days!

**Comment by Swatilekha-Roy** [comment]
I really want to contribute to this issue please, could you kindly assign me? Thanks.
My Discord id is oh_laugh_hugs and I am a mentee in JWOC.

**Comment by Ayushee11** [comment]
Hi...i want to be a part of it....may u assign it to me

**Comment by kanishkaa24** [comment]
Hello Mam, Can I work on this as a part of CrossWoC?
