### ISSUE TITLE
Design a blog page

### ISSUE THREAD

**Issue by chehak123** [chehak123/GirlMeetup#15]
This page would contain experiences of different people who were a part of the scholarship programs and a comment section for those who need to ask some doubts. 
This can also include some related youtube videos.

**Comment by pawki07** [comment]
Do we need to use HTML/ CSS and javascript for this page? If yes, then I can work on this.

**Comment by chehak123** [comment]
@pawki07 you need to design it using bootstrap

**Comment by anushruti11** [comment]
I would like to work on this.

**Comment by pawki07** [comment]
I can work on this issue.

**Comment by chehak123** [comment]
@pawki07 go ahead

**Comment by karunkarthik-git** [comment]
I'd love to work on this issue. Kindly assign me this @chehak123 !

**Comment by chehak123** [comment]
Go ahead @karunkarthik-git
