### ISSUE TITLE
Add FAQs section on homepage

### ISSUE THREAD

**Issue by chehak123** [chehak123/GirlMeetup#18]
Add drop-down accordions for FAQs.
Use bootstrap.
Add relevant content as well

**Comment by Swatilekha-Roy** [comment]
I really want to contribute to this issue please, could you kindly assign me? Thanks.
My Discord id is oh_laugh_hugs and I am a mentee in JWOC.

**Comment by chehak123** [comment]
Go ahead @Swatilekha-Roy
