### ISSUE TITLE
Create content for the website

### ISSUE THREAD

**Issue by ineffable23** [chehak123/GirlMeetup#19]
Create eye catchy, unique and interactive content for the website in laymen language.

**Comment by AtharvaParkale** [comment]
> Create eye catchy, unique and interactive content for the website in laymen language.

I would like to contribute.

**Comment by ineffable23** [comment]
@AtharvaParkale Go ahead 👍

**Comment by AtharvaParkale** [comment]
> @AtharvaParkale Go ahead 👍
> 
> Do share screenshots of your work while making PR.

Could you tell me what are your requirements for this project?
What do you expect from me?

**Comment by ineffable23** [comment]
@AtharvaParkale Replace the Lorem Ipsum with some appropriate content of your choice. Share your ideas regarding the same with some screenshots of the work for better understanding.

**Comment by AtharvaParkale** [comment]
> @AtharvaParkale Replace the Lorem Ipsum with some appropriate content of your choice. Share your ideas regarding the same with some screenshots of the work for better understanding.

Okay
