### ISSUE TITLE
Create an about us section on homepage

### ISSUE THREAD

**Issue by chehak123** [chehak123/GirlMeetup#23]

**Comment by syedmazharaliraza** [comment]
greetings mentor, can I work on this issue

**Comment by harshita2216** [comment]
I would like to contribute to this issue. (JWoC Mentee)

**Comment by karunkarthik-git** [comment]
I'd like to work on this issue! Kindly assign it to me! @chehak123

**Comment by chehak123** [comment]
Go ahead @karunkarthik-git
