### ISSUE TITLE
Create header and footer with all the necessary details

### ISSUE THREAD

**Issue by chehak123** [chehak123/GirlMeetup#3]
1. Design the navbar and header for homepage using Bootstrap.
2. Also design a uniform header for all other pages.
3. Footer include - 1) navbar links  2) some information about the site  3) subscribe to newsletter option

**Comment by chehak123** [comment]
Yeah go ahead!! @Malvika18

**Comment by chehak123** [comment]
Yea sure you can work on it after the coding period begins.

**Comment by RounakNeogy** [comment]
i want to contribute

**Comment by magjoy6** [comment]
Hello @chehak123 I also want to work on this

**Comment by Niveditha18** [comment]
Hey @chehak123, I want to work on this issue

**Comment by anushruti11** [comment]
Hey, I want to work on this.

**Comment by karunkarthik-git** [comment]
@chehak123  I'd like to contribute to this issue as a mentee of JWOC. Could you assign it ?

**Comment by sneha-baser** [comment]
as per  instructions on taking up the issue on 20th Jan after 10p.m(Under JWOC),   I am part of JWOC as mentee and i wanna contribute to this issue.

**Comment by harshita2216** [comment]
I would like to contribute to this issue. (Mentee at JWOC)

**Comment by sneha-baser** [comment]
as per instructions on taking up the issue on 20th Jan after 10p.m(Under JWOC), I am part of JWOC as mentee and i wanna contribute to this issue.

**Comment by chehak123** [comment]
Go ahead @Malvika18

**Comment by Malvika18** [comment]
@chehak123 please review my PR.

**Comment by Swatilekha-Roy** [comment]
I want to contribute to this issue.

**Comment by chehak123** [comment]
@Swatilekha-Roy you can work on this issue.

**Comment by chehak123** [comment]
@karunkarthik-git you can go ahead with this issue

**Comment by Swatilekha-Roy** [comment]
Hi @chehak123 I already started working on the issue. Can I not continue instead? Please.
