### ISSUE TITLE
Add contributing.md

### ISSUE THREAD

**Issue by chehak123** [chehak123/GirlMeetup#4]

**Comment by luckykumarirai** [comment]
I would like to work on it as a participant of jwoc.

**Comment by karunkarthik-git** [comment]
I'd like to contribute to this issue as a mentee of JWOC.

**Comment by tusharjain0022** [comment]
I would like to work on this issue as a mentee of JWOC. It would be great if you could assign this issue to me along with #5 . If you wish I can also add Issue and PR templates for this repository while resolving these two issues.

**Comment by chehak123** [comment]
Go ahead @luckykumarirai

**Comment by luckykumarirai** [comment]
Hello, @chehak123 I have sent PR after adding contributing file please review it.
