### ISSUE TITLE
Enhance Readme.md

### ISSUE THREAD

**Issue by chehak123** [chehak123/GirlMeetup#5]
1. Add some gifs, and make it more attractive and innovative
2. Add a section of project contributors
3. Add the list of open source organisations this project has been part of
4. Add the tech stack of the project.
5. Add the logo and screenshots of the mainpage

**Comment by pawki07** [comment]
I would like to contribute to this issue. Please assign it to me.

**Comment by shreetama123** [comment]
I would like to contribute in this .

**Comment by tusharjain0022** [comment]
I would like to work on this issue. It would be great if you could assign this issue to me along with #4 . If you wish I can also add Issue and PR templates for this repository while resolving these two issues.

**Comment by chehak123** [comment]
Go ahead @pawki07.

**Comment by pawki07** [comment]
Okay, I have started working on it.

**Comment by pawki07** [comment]
@chehak123 can you please provide the logo and screenshots of the mainpage

**Comment by chehak123** [comment]
> @chehak123 can you please provide the logo and screenshots of the mainpage

that can be added later
