### ISSUE TITLE
Register bug

### ISSUE THREAD

**Issue by nishant23122000** [chehak123/GirlMeetup#60]
i found one register issue
Whenever new user register in website and click register button then our backend POST /register execute

> User.register(
    new User({
      username: req.body.username,
      name: req.body.name,
    }),
    req.body.password,
    function (err, user) {
      if (err) {
        console.log(err);
        res.render("register");
      }
      passport.authenticate("local")(req, res, function () {
        console.log(req.baseUrl);
        res.redirect("/" + "#login_new_user");
      });
    }
  );

  res.render("index");
}

Database take some time to validate user and due to asynchronous behaviour of JS the last line res.render("index") execute first and will give EJS error

Solution:
we can remove res.render("index") and replace res.redirect("/" + "#login_new_user"); with res.redirect("/")

**Comment by Amool-kk** [comment]
can I work on this issue. This will be complete in 4-5 days

**Comment by nishant23122000** [comment]
i already did it. So it will be better assign this issue to me

**Comment by chehak123** [comment]
Go ahead @nishant23122000
