### ISSUE TITLE
Add Login and SignUp Pages

### ISSUE THREAD

**Issue by chehak123** [chehak123/GirlMeetup#7]

**Comment by anushruti11** [comment]
I would like  to contribute to its frontend part.

**Comment by uttu2** [comment]
I would like to contribute in frontend part

**Comment by harshita2216** [comment]
I would like to contribute to this issue. (Mentee at JWOC)

**Comment by chehak123** [comment]
Both frontend and backend needs to be completed in this issue. Go ahead @harshita2216 .

**Comment by mak-ux** [comment]
someone is working on this issue ? Both front and back? If not I can work on all the authentication part, login, signup, validation?

**Comment by karunkarthik-git** [comment]
If this issue is free I'd like to work on it. Kindly assign this to me @chehak123 !
