### ISSUE TITLE
Add a scholarship section on home page

### ISSUE THREAD

**Issue by chehak123** [chehak123/GirlMeetup#8]
Add some on going scholarships on the main page and add a redirect link to scholarship page

**Comment by Sayak-0512** [comment]
I would like to work on this issue!
Part of JWOC!

**Comment by chehak123** [comment]
Share your design here first then start working on it

**Comment by Swatilekha-Roy** [comment]
I want to contribute to this issue.

**Comment by Sayak-0512** [comment]
I have added a scholarship section and have made a PR. Please see to it!

**Comment by chehak123** [comment]
Go ahaed @Swatilekha-Roy

**Comment by Swatilekha-Roy** [comment]
Okay, @chehak123.

**Comment by karunkarthik-git** [comment]
I'd love to work on this issue. Assign it to me @chehak123 if it's open!
